#!/bin/sh

#Autores: Fernando Dellão Menini 201935005,
#         Luccas de Macedo Sodré 201535013

if [ "$1" == "clean" ]; then
		rm *.class src/*.class
		echo "Todos arquivos '.class' apagados."
else
		jflex src/Specification.jflex
		javac *.java

fi
