// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: src/Specification.jflex

/*Autores: Fernando Dellão Menini 201935005,
           Luccas de Macedo Sodré 201535013
*/
    //Codigo do Usuário

package src;

// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class Lexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int COMMENT = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\5\u0900\1\u0a00\1\u0b00\1\u0c00\2\u0800\1\u0d00\3\u0800"+
    "\1\u0e00\1\u0f00\1\u1000\1\u1100\1\u1200\1\u1300\1\u1400\1\u1500"+
    "\1\u1600\1\u1700\1\u1800\2\u0800\1\u1900\7\u0800\1\u1a00\1\u1b00"+
    "\170\u0800\1\u1c00\1\u1d00\1\u1e00\1\u1f00\1\u2000\1\u2100\54\u0800"+
    "\10\u2200\33\u0800\1\u2300\3\u0800\1\u2400\4\u0800\1\u2500\7\u0800"+
    "\1\u2600\1\u2700\2\u0800\1\u2800\1\u2900\1\u2a00\1\u0800\1\u0a00"+
    "\1\u0800\1\u2b00\1\u2700\1\u2c00\3\u0800\1\u2000\1\u2d00\114\u0800"+
    "\1\u2e00\1\u2000\2\u0800\1\u2f00\145\u0800\1\u3000\1\u3100\1\u3200"+
    "\1\u3300\11\u0800\1\u3400\1\u2a00\6\u0800\1\u3500\7\u0800\1\u3600"+
    "\u0f0e\u0800";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\6"+
    "\1\7\3\0\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\11\24\1\25"+
    "\1\26\1\27\1\30\1\31\2\0\32\32\1\33\1\34"+
    "\1\35\1\0\1\36\1\0\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\47\1\45\1\46\1\50"+
    "\1\46\1\51\1\41\1\52\1\46\1\53\1\54\1\55"+
    "\1\56\1\46\1\57\3\46\1\60\1\61\1\62\7\0"+
    "\1\3\44\0\1\46\12\0\1\46\4\0\1\46\5\0"+
    "\27\32\1\0\7\32\30\46\1\0\10\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\2\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\2\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\2\32\1\46\1\32\1\46"+
    "\1\32\3\46\2\32\1\46\1\32\1\46\2\32\1\46"+
    "\3\32\2\46\4\32\1\46\2\32\1\46\3\32\3\46"+
    "\2\32\1\46\2\32\1\46\1\32\1\46\1\32\1\46"+
    "\2\32\1\46\1\32\2\46\1\32\1\46\2\32\1\46"+
    "\3\32\1\46\1\32\1\46\2\32\2\46\1\0\1\32"+
    "\3\46\4\0\1\32\1\0\1\46\1\32\1\0\1\46"+
    "\1\32\1\0\1\46\1\32\1\46\1\32\1\46\1\32"+
    "\1\46\1\32\1\46\1\32\1\46\1\32\1\46\1\32"+
    "\1\46\1\32\2\46\1\32\1\46\1\32\1\46\1\32"+
    "\1\46\1\32\1\46\1\32\1\46\1\32\1\46\1\32"+
    "\1\46\1\32\1\46\1\32\2\46\1\32\1\0\1\46"+
    "\1\32\1\46\3\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\7\46\2\32\1\46"+
    "\2\32\2\46\1\32\1\46\4\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\105\46\1\0\44\46"+
    "\7\0\2\46\36\0\5\46\140\0\1\46\52\0\1\32"+
    "\1\46\1\32\1\46\2\0\1\32\1\46\2\0\4\46"+
    "\1\0\1\32\6\0\1\32\1\0\3\32\1\0\1\32"+
    "\1\0\2\32\1\46\21\32\1\0\11\32\43\46\1\32"+
    "\2\46\3\32\3\46\1\32\1\46\1\32\1\46\1\32"+
    "\1\46\1\32\1\46\1\32\1\46\1\32\1\46\1\32"+
    "\1\46\1\32\1\46\1\32\1\46\1\32\1\46\1\32"+
    "\1\46\1\32\5\46\1\32\1\46\1\0\1\32\1\46"+
    "\2\32\2\46\63\32\60\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\10\0\1\32"+
    "\1\46\1\32\1\46\1\32\1\46\1\32\1\46\1\32"+
    "\1\46\1\32\1\46\1\32\1\46\1\32\1\46\1\32"+
    "\1\46\1\32\1\46\1\32\1\46\1\32\1\46\1\32"+
    "\1\46\1\32\1\46\1\32\1\46\1\32\1\46\1\32"+
    "\1\46\1\32\1\46\1\32\1\46\1\32\1\46\1\32"+
    "\1\46\1\32\1\46\1\32\1\46\1\32\1\46\1\32"+
    "\1\46\1\32\1\46\1\32\1\46\2\32\1\46\1\32"+
    "\1\46\1\32\1\46\1\32\1\46\1\32\1\46\1\32"+
    "\1\46\1\32\2\46\1\32\1\46\1\32\1\46\1\32"+
    "\1\46\1\32\1\46\1\32\1\46\1\32\1\46\1\32"+
    "\1\46\1\32\1\46\1\32\1\46\1\32\1\46\1\32"+
    "\1\46\1\32\1\46\1\32\1\46\1\32\1\46\1\32"+
    "\1\46\1\32\1\46\1\32\1\46\1\32\1\46\1\32"+
    "\1\46\1\32\1\46\1\32\1\46\1\32\1\46\1\32"+
    "\1\46\1\32\1\46\1\32\1\46\1\32\1\46\1\32"+
    "\1\46\1\32\1\46\1\32\1\46\1\32\1\46\1\32"+
    "\1\46\1\32\1\46\1\32\1\46\1\32\1\46\1\32"+
    "\1\46\1\32\1\46\1\32\1\46\1\32\1\46\1\32"+
    "\1\46\1\32\1\46\1\32\1\46\1\32\1\46\1\32"+
    "\1\46\1\32\1\46\1\32\1\46\1\32\1\46\1\32"+
    "\1\46\1\32\1\46\1\0\46\32\11\0\51\46\327\0"+
    "\12\63\206\0\12\63\306\0\12\63\u019c\0\12\63\166\0"+
    "\12\63\140\0\12\63\166\0\12\63\106\0\12\63\u0116\0"+
    "\12\63\106\0\12\63\6\0\46\32\1\0\1\32\5\0"+
    "\1\32\2\0\53\46\2\0\3\46\240\0\126\32\2\0"+
    "\6\46\342\0\12\63\46\0\12\63\u012c\0\12\63\200\0"+
    "\12\63\246\0\12\63\6\0\12\63\266\0\12\63\126\0"+
    "\12\63\206\0\12\63\6\0\12\63\46\0\11\46\7\0"+
    "\53\32\2\0\3\32\100\0\300\46\100\0\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\11\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\11\46\10\32\6\46"+
    "\2\0\6\32\2\0\10\46\10\32\10\46\10\32\6\46"+
    "\2\0\6\32\2\0\10\46\1\0\1\32\1\0\1\32"+
    "\1\0\1\32\1\0\1\32\10\46\10\32\16\46\2\0"+
    "\10\46\10\0\10\46\10\0\10\46\10\0\5\46\1\0"+
    "\2\46\4\32\2\0\1\46\3\0\3\46\1\0\2\46"+
    "\4\32\4\0\4\46\2\0\2\46\4\32\4\0\10\46"+
    "\5\32\5\0\3\46\1\0\2\46\4\32\54\0\2\3"+
    "\107\0\1\46\15\0\1\46\20\0\15\46\145\0\1\32"+
    "\4\0\1\32\2\0\1\46\3\32\2\46\3\32\1\46"+
    "\1\0\1\32\3\0\5\32\6\0\1\32\1\0\1\32"+
    "\1\0\1\32\1\0\4\32\1\0\1\46\4\32\1\46"+
    "\4\0\1\46\2\0\2\46\2\32\5\0\1\32\4\46"+
    "\4\0\1\46\21\0\20\32\20\46\3\0\1\32\1\46"+
    "\u0131\0\32\32\32\46\26\0\57\32\1\0\57\46\1\0"+
    "\1\32\1\46\3\32\2\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\4\32\1\46\1\32\2\46\1\32\10\46"+
    "\3\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\2\46\6\0\1\32\1\46\1\32"+
    "\1\46\3\0\1\32\1\46\14\0\46\46\1\0\1\46"+
    "\5\0\1\46\362\0\12\63\26\0\1\32\1\46\1\32"+
    "\1\46\1\32\1\46\1\32\1\46\1\32\1\46\1\32"+
    "\1\46\1\32\1\46\1\32\1\46\1\32\1\46\1\32"+
    "\1\46\1\32\1\46\1\32\1\46\1\32\1\46\1\32"+
    "\1\46\1\32\1\46\1\32\1\46\1\32\1\46\1\32"+
    "\1\46\1\32\1\46\1\32\1\46\1\32\1\46\1\32"+
    "\1\46\1\32\1\46\22\0\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\1\46"+
    "\1\32\1\46\1\32\1\46\1\32\1\46\1\32\3\46"+
    "\204\0\1\32\1\46\1\32\1\46\1\32\1\46\1\32"+
    "\1\46\1\32\1\46\1\32\1\46\1\32\3\46\1\32"+
    "\1\46\1\32\1\46\1\32\1\46\1\32\1\46\1\32"+
    "\1\46\1\32\1\46\1\32\1\46\1\32\1\46\1\32"+
    "\1\46\1\32\1\46\1\32\1\46\1\32\1\46\1\32"+
    "\1\46\1\32\1\46\1\32\1\46\1\32\1\46\1\32"+
    "\1\46\1\32\1\46\1\32\1\46\1\32\1\46\1\32"+
    "\1\46\1\32\1\46\1\32\1\46\1\32\1\46\1\32"+
    "\1\46\1\32\1\46\1\32\1\46\1\32\1\46\1\32"+
    "\1\46\1\32\1\46\1\32\12\46\1\32\1\46\1\32"+
    "\1\46\2\32\1\46\1\32\1\46\1\32\1\46\1\32"+
    "\1\46\1\32\1\46\3\0\1\32\1\46\1\32\1\46"+
    "\1\0\1\32\1\46\1\32\3\46\1\32\1\46\1\32"+
    "\1\46\1\32\1\46\1\32\1\46\1\32\1\46\1\32"+
    "\1\46\1\32\1\46\1\32\1\46\1\32\1\46\1\32"+
    "\1\46\5\32\1\46\5\32\1\46\1\32\1\46\1\32"+
    "\1\46\1\32\1\46\1\32\1\46\1\32\1\46\2\0"+
    "\1\32\1\46\3\32\61\0\3\46\325\0\12\63\46\0"+
    "\12\63\306\0\12\63\26\0\12\63\126\0\12\63\326\0"+
    "\53\46\1\0\14\46\10\0\120\46\60\0\12\63\6\0"+
    "\u0100\3\7\46\14\0\5\46\370\0\12\63\7\0\32\32"+
    "\6\0\32\46\245\0\50\32\50\46\120\0\12\63\6\0"+
    "\44\32\4\0\44\46\204\0\63\32\15\0\63\46\75\0"+
    "\12\63\u012c\0\12\63\200\0\12\63\74\0\12\63\220\0"+
    "\12\63\u0116\0\12\63\126\0\12\63\146\0\12\63\326\0"+
    "\40\32\40\46\12\63\146\0\12\63\106\0\12\63\266\0"+
    "\12\63\326\0\40\32\40\46\200\0\32\32\32\46\32\32"+
    "\7\46\1\0\22\46\32\32\32\46\1\32\1\0\2\32"+
    "\2\0\1\32\2\0\2\32\2\0\4\32\1\0\10\32"+
    "\4\46\1\0\1\46\1\0\7\46\1\0\13\46\32\32"+
    "\32\46\2\32\1\0\4\32\2\0\10\32\1\0\7\32"+
    "\1\0\32\46\2\32\1\0\4\32\1\0\5\32\1\0"+
    "\1\32\3\0\7\32\1\0\32\46\32\32\32\46\32\32"+
    "\32\46\32\32\32\46\32\32\32\46\32\32\32\46\32\32"+
    "\34\46\2\0\31\32\1\0\31\46\1\0\6\46\31\32"+
    "\1\0\31\46\1\0\6\46\31\32\1\0\31\46\1\0"+
    "\6\46\31\32\1\0\31\46\1\0\6\46\31\32\1\0"+
    "\31\46\1\0\6\46\1\32\1\46\2\0\62\63\100\0"+
    "\12\63\266\0\42\32\42\46\14\0\12\63\326\0\32\32"+
    "\6\0\32\32\6\0\32\32\166\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[14080];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\1\3\1\4\2\1\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\2\15\1\1"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\11\25"+
    "\1\26\1\27\1\2\1\30\1\31\3\0\1\32\1\0"+
    "\1\15\1\33\1\34\1\0\1\25\1\0\1\35\2\25"+
    "\1\0\3\25\1\36\1\37\1\40\3\0\1\25\1\41"+
    "\1\0\1\25\1\0\1\25\1\0\1\42\1\43\1\0"+
    "\1\25\1\44\1\0\1\45\1\0\1\46\1\47\1\0"+
    "\1\50\2\0\1\51\1\52";

  private static int [] zzUnpackAction() {
    int [] result = new int[88];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\64\0\150\0\150\0\234\0\320\0\150\0\u0104"+
    "\0\u0138\0\150\0\150\0\150\0\150\0\150\0\u016c\0\u01a0"+
    "\0\150\0\150\0\u01d4\0\u0208\0\150\0\150\0\u023c\0\150"+
    "\0\u0270\0\150\0\150\0\u02a4\0\u02d8\0\u030c\0\u0340\0\u0374"+
    "\0\u03a8\0\u03dc\0\u0410\0\u0444\0\u0478\0\150\0\u04ac\0\150"+
    "\0\150\0\u04e0\0\u0514\0\u0548\0\u01a0\0\u01a0\0\u057c\0\150"+
    "\0\150\0\u05b0\0\u05e4\0\u0618\0\150\0\u064c\0\u0680\0\u06b4"+
    "\0\u06e8\0\u071c\0\u0750\0\150\0\150\0\150\0\u0784\0\u07b8"+
    "\0\u07ec\0\u0820\0\150\0\u0854\0\u0888\0\u08bc\0\u08f0\0\u0924"+
    "\0\150\0\150\0\u0958\0\u098c\0\150\0\u09c0\0\150\0\u09f4"+
    "\0\150\0\150\0\u0a28\0\150\0\u0a5c\0\u0a90\0\150\0\150";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[88];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\3\1\4\1\5\1\4\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\3\1\33\1\3\3\34\1\35"+
    "\1\36\1\37\2\34\1\40\1\34\1\41\1\42\1\43"+
    "\1\34\1\44\2\34\1\45\1\3\1\46\1\3\20\4"+
    "\1\3\37\4\1\47\1\4\1\3\1\4\66\0\1\4"+
    "\111\0\1\50\44\0\1\51\77\0\1\52\6\0\1\53"+
    "\2\0\1\52\1\0\1\52\1\0\1\52\4\0\1\52"+
    "\3\0\1\52\2\0\1\52\24\0\1\54\66\0\2\55"+
    "\60\0\1\56\1\0\1\57\1\23\36\0\1\57\25\0"+
    "\1\60\66\0\1\61\41\0\1\31\3\0\1\31\12\0"+
    "\1\31\10\0\1\31\3\0\2\31\1\0\1\31\1\0"+
    "\2\31\2\0\1\31\1\0\1\31\3\0\1\31\10\0"+
    "\1\34\3\0\1\34\12\0\1\34\10\0\1\34\3\0"+
    "\2\34\1\0\1\34\1\0\2\34\2\0\1\34\1\0"+
    "\1\34\3\0\1\34\10\0\1\34\3\0\1\34\12\0"+
    "\1\34\10\0\1\34\1\62\2\0\2\34\1\0\1\34"+
    "\1\0\2\34\2\0\1\34\1\0\1\34\3\0\1\34"+
    "\10\0\1\34\3\0\1\34\12\0\1\34\10\0\1\34"+
    "\3\0\2\34\1\0\1\34\1\0\1\34\1\63\2\0"+
    "\1\34\1\0\1\34\3\0\1\34\10\0\1\34\3\0"+
    "\1\34\12\0\1\34\10\0\1\34\1\64\2\0\2\34"+
    "\1\0\1\34\1\0\2\34\2\0\1\34\1\0\1\34"+
    "\3\0\1\34\10\0\1\34\3\0\1\34\12\0\1\34"+
    "\10\0\1\34\3\0\2\34\1\65\1\34\1\0\2\34"+
    "\2\0\1\34\1\0\1\66\3\0\1\34\10\0\1\34"+
    "\3\0\1\34\12\0\1\34\10\0\1\34\3\0\1\34"+
    "\1\67\1\0\1\34\1\0\2\34\2\0\1\34\1\0"+
    "\1\34\1\70\2\0\1\34\10\0\1\34\3\0\1\34"+
    "\12\0\1\34\10\0\1\34\3\0\2\34\1\0\1\34"+
    "\1\0\2\34\2\0\1\71\1\0\1\34\3\0\1\34"+
    "\10\0\1\34\3\0\1\34\12\0\1\34\10\0\1\34"+
    "\3\0\1\34\1\72\1\0\1\34\1\0\2\34\2\0"+
    "\1\34\1\0\1\34\3\0\1\34\10\0\1\34\3\0"+
    "\1\34\12\0\1\34\10\0\1\34\3\0\2\34\1\0"+
    "\1\34\1\0\2\34\2\0\1\73\1\0\1\34\3\0"+
    "\1\34\22\0\1\74\63\0\1\75\55\0\1\76\57\0"+
    "\1\52\3\0\1\52\21\0\1\52\3\0\1\52\10\0"+
    "\1\52\1\0\1\52\1\0\1\52\3\0\1\52\2\0"+
    "\2\54\1\4\2\0\1\5\56\54\23\0\2\57\36\0"+
    "\1\57\55\0\1\77\14\0\1\34\3\0\1\34\12\0"+
    "\1\34\10\0\1\34\3\0\2\34\1\0\1\34\1\0"+
    "\2\34\2\0\1\34\1\100\1\34\3\0\1\34\52\0"+
    "\1\101\21\0\1\34\3\0\1\34\12\0\1\34\10\0"+
    "\1\34\3\0\1\34\1\102\1\0\1\34\1\0\2\34"+
    "\2\0\1\34\1\0\1\34\3\0\1\34\10\0\1\34"+
    "\3\0\1\34\12\0\1\34\10\0\1\34\3\0\2\34"+
    "\1\0\1\34\1\0\2\34\2\0\1\34\1\0\1\34"+
    "\1\0\1\103\1\0\1\34\52\0\1\104\21\0\1\34"+
    "\3\0\1\34\12\0\1\34\10\0\1\34\3\0\2\34"+
    "\1\0\1\34\1\0\1\105\1\34\2\0\1\34\1\0"+
    "\1\34\3\0\1\34\10\0\1\34\3\0\1\34\12\0"+
    "\1\34\10\0\1\34\1\106\2\0\2\34\1\0\1\34"+
    "\1\0\2\34\2\0\1\34\1\0\1\107\3\0\1\34"+
    "\10\0\1\34\3\0\1\34\12\0\1\34\10\0\1\34"+
    "\3\0\2\34\1\0\1\34\1\0\2\34\2\0\1\34"+
    "\1\0\1\34\1\110\2\0\1\34\41\0\1\111\67\0"+
    "\1\112\74\0\1\113\15\0\1\34\3\0\1\34\12\0"+
    "\1\34\10\0\1\34\3\0\2\34\1\0\1\34\1\0"+
    "\2\34\2\0\1\114\1\0\1\34\3\0\1\34\52\0"+
    "\1\115\21\0\1\34\3\0\1\34\12\0\1\34\10\0"+
    "\1\34\3\0\2\34\1\0\1\34\1\0\2\34\1\116"+
    "\1\0\1\34\1\0\1\34\3\0\1\34\44\0\1\117"+
    "\27\0\1\34\3\0\1\34\12\0\1\34\10\0\1\34"+
    "\3\0\2\34\1\0\1\34\1\0\2\34\2\0\1\34"+
    "\1\0\1\34\1\120\2\0\1\34\45\0\1\121\63\0"+
    "\1\122\26\0\1\34\3\0\1\34\12\0\1\34\10\0"+
    "\1\34\1\123\2\0\2\34\1\0\1\34\1\0\2\34"+
    "\2\0\1\34\1\0\1\34\3\0\1\34\57\0\1\124"+
    "\61\0\1\125\65\0\1\126\57\0\1\127\55\0\1\130"+
    "\20\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2756];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\2\11\2\1\1\11\2\1\5\11\2\1\2\11"+
    "\2\1\2\11\1\1\1\11\1\1\2\11\12\1\1\11"+
    "\1\1\2\11\3\0\1\1\1\0\1\1\2\11\1\0"+
    "\1\1\1\0\1\11\2\1\1\0\3\1\3\11\3\0"+
    "\1\1\1\11\1\0\1\1\1\0\1\1\1\0\2\11"+
    "\1\0\1\1\1\11\1\0\1\11\1\0\2\11\1\0"+
    "\1\11\2\0\2\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[88];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    //Inserção de código arbitrário

    private int ntk;

    public int readedTokens(){
        return ntk;
    }

    private Token symbol(TokenType t){
        ntk++;
        return new Token(t, yytext(), yyline + 1, yycolumn + 1);
    }

    private Token symbol(TokenType t, Object value){
        ntk++;
        return new Token(t, value, yyline + 1, yycolumn + 1);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
      ntk = 0;
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token nextToken() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { throw new RuntimeException("Illegal character <"+yytext()+">");
            }
            // fall through
          case 43: break;
          case 2:
            { 
            }
            // fall through
          case 44: break;
          case 3:
            { return symbol(TokenType.LOGICAL_NOT);
            }
            // fall through
          case 45: break;
          case 4:
            { return symbol(TokenType.MODULUS);
            }
            // fall through
          case 46: break;
          case 5:
            { return symbol(TokenType.LEFT_PARENTHESIS);
            }
            // fall through
          case 47: break;
          case 6:
            { return symbol(TokenType.RIGHT_PARENTHESIS);
            }
            // fall through
          case 48: break;
          case 7:
            { return symbol(TokenType.TIMES);
            }
            // fall through
          case 49: break;
          case 8:
            { return symbol(TokenType.PLUS);
            }
            // fall through
          case 50: break;
          case 9:
            { return symbol(TokenType.COMMA);
            }
            // fall through
          case 51: break;
          case 10:
            { return symbol(TokenType.MINUS);
            }
            // fall through
          case 52: break;
          case 11:
            { return symbol(TokenType.DOT);
            }
            // fall through
          case 53: break;
          case 12:
            { return symbol(TokenType.DIVISION);
            }
            // fall through
          case 54: break;
          case 13:
            { return symbol(TokenType.INT);
            }
            // fall through
          case 55: break;
          case 14:
            { return symbol(TokenType.SEMI);
            }
            // fall through
          case 56: break;
          case 15:
            { return symbol(TokenType.LESS_THAN);
            }
            // fall through
          case 57: break;
          case 16:
            { return symbol(TokenType.EQ);
            }
            // fall through
          case 58: break;
          case 17:
            { return symbol(TokenType.GREATER_THAN);
            }
            // fall through
          case 59: break;
          case 18:
            { return symbol(TokenType.TYPE_ID);
            }
            // fall through
          case 60: break;
          case 19:
            { return symbol(TokenType.LEFT_SQUARE_BRACKETS);
            }
            // fall through
          case 61: break;
          case 20:
            { return symbol(TokenType.RIGHT_SQUARE_BRACKETS);
            }
            // fall through
          case 62: break;
          case 21:
            { return symbol(TokenType.VARIABLE_ID);
            }
            // fall through
          case 63: break;
          case 22:
            { return symbol(TokenType.LEFT_CURLY_BRACES);
            }
            // fall through
          case 64: break;
          case 23:
            { return symbol(TokenType.RIGHT_CURLY_BRACES);
            }
            // fall through
          case 65: break;
          case 24:
            { return symbol(TokenType.DIFFERENT);
            }
            // fall through
          case 66: break;
          case 25:
            { return symbol(TokenType.LOGICAL_AND);
            }
            // fall through
          case 67: break;
          case 26:
            { return symbol(TokenType.FLOAT);
            }
            // fall through
          case 68: break;
          case 27:
            { return symbol(TokenType.TYPE_DEFINITION);
            }
            // fall through
          case 69: break;
          case 28:
            { return symbol(TokenType.EQUAL_TO);
            }
            // fall through
          case 70: break;
          case 29:
            { return symbol(TokenType.IF);
            }
            // fall through
          case 71: break;
          case 30:
            { yybegin(COMMENT);
            }
            // fall through
          case 72: break;
          case 31:
            { yybegin(YYINITIAL);
            }
            // fall through
          case 73: break;
          case 32:
            { return symbol(TokenType.CHAR);
            }
            // fall through
          case 74: break;
          case 33:
            { return symbol(TokenType.NEW);
            }
            // fall through
          case 75: break;
          case 34:
            { return symbol(TokenType.DATA);
            }
            // fall through
          case 76: break;
          case 35:
            { return symbol(TokenType.ELSE);
            }
            // fall through
          case 77: break;
          case 36:
            { return symbol(TokenType.NULL);
            }
            // fall through
          case 78: break;
          case 37:
            { return symbol(TokenType.READ);
            }
            // fall through
          case 79: break;
          case 38:
            { return symbol(TokenType.TRUE);
            }
            // fall through
          case 80: break;
          case 39:
            { return symbol(TokenType.FALSE);
            }
            // fall through
          case 81: break;
          case 40:
            { return symbol(TokenType.PRINT);
            }
            // fall through
          case 82: break;
          case 41:
            { return symbol(TokenType.RETURN);
            }
            // fall through
          case 83: break;
          case 42:
            { return symbol(TokenType.ITERATE);
            }
            // fall through
          case 84: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
